### ISSUE TITLE
unhandled exception when there is no Internet connectivity

### ISSUE THREAD

**Issue by probonopd** [jayhasyee/astroffers#38]
The application throws an unhandled exception when there is no Internet connectivity:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/0c1557e491195a8759ff6edfd12dedf3165e243d/database/Astroffers/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/448

**Comment by hasyee** [comment]
Thanks for your report, I also met this issue today evening when I turned back my computer from sleeping. I think electron-updater will fix this issue. Until that I will catch this exception.

**Comment by probonopd** [comment]
Thanks @jayhasyee, if you could ping me once the new release is available for download I can include it in [AppImageHub](https://appimage.github.io/apps/).

**Comment by hasyee** [comment]
There is available since today: http://astroffers.org/

**Comment by probonopd** [comment]
Thank you, working.
